server:
  port: 8090

spring:
  application:
    name: app

tracing:
  #ye OLTP trace endpoint h jaha pr ye apne traces bhejti h jo jaegar recieve
  #krta h apne UI mei
  url: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
